use pc_hevodata_db;

SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count
FROM PC_HEVODATA_DB.PUBLIC.CUSTOMERS
UNION ALL
SELECT 'ORDERS', COUNT(*)
FROM PC_HEVODATA_DB.PUBLIC.ORDERS
UNION ALL
SELECT 'FEEDBACK', COUNT(*)
FROM PC_HEVODATA_DB.PUBLIC.FEEDBACK;


SELECT 'ORDER_EVENTS', COUNT(*)
FROM PC_HEVODATA_DB.PUBLIC.ORDER_EVENTS
UNION ALL
SELECT 'CUSTOMER_CLEAN', COUNT(*)
FROM PC_HEVODATA_DB.PUBLIC.CUSTOMERS_ENRICHED;

SELECT * FROM PC_HEVODATA_DB.PUBLIC.ORDER_EVENTS;

SELECT * FROM PC_HEVODATA_DB.PUBLIC.CUSTOMERS_ENRICHED
LIMIT 20;
